### ISSUE TITLE
Broken markup in section 38.6

### ISSUE THREAD

**Issue by mats852** [beejjorgensen/bgc#113]
There is broken markup at the end of this page

https://beej.us/guide/bgc/html/split-wide/date-and-time-functionality.html

https://github.com/beejjorgensen/bgc/blob/3eb1f01553c9f6bb04de0b24ace1727d6f508a82/src/bgc_part_3300_time.md?plain=1#L464-L466

**Comment by beejjorgensen** [comment]
Fixed in next release. Thanks!
