### ISSUE TITLE
12.5 Changing Allocated Size with realloc() :: sizeof(*p)

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#12]
That call
```
float *p = malloc(sizeof *p * 20);
```
Is a little surprising. `p` hasn't been defined before and your are using itself in its own definition.
Adding a line on why it's valid and that it would even work if p was assigned to NULL (which you do several lines after).
I naively thought that perhaps the pointer is being dereferenced, that is why it would work (after doing some research, I understand now that it's not).

Just a thought.
(Please take this comment as, if it makes sense to you and if you have time, but demands no explanation or justification on your part)

**Comment by beejjorgensen** [comment]
Good feedback. Added clarifications to that effect. Thanks!
