### ISSUE TITLE
change font type serif to sans-serif

### ISSUE THREAD

**Issue by huseyin1419** [beejjorgensen/bgc#131]
can you change font type serif to sans-serif on printed version and web page.
serif is tiring to read but sans-serif is more readable, easy on eyes.

**Comment by beejjorgensen** [comment]
Hmm. I personally can't stand sans in print, so I'm unlikely to change that. But on the web pages, I agree it can be easier... I'll consider it.

**Comment by zlate42** [comment]
> can you change font type serif to sans-serif on printed version and web page. serif is tiring to read but sans-serif is more readable, easy on eyes.

You can build it yourself with any font you like. Just change the line with PDF_MAINFONT="Liberation Serif" in src/Makefile and build it by yourself. If you are having trouble with building, I can build it for you, if you like.

**Comment by huseyin1419** [comment]
> You can build it yourself with any font you like. Just change the line with PDF_MAINFONT="Liberation Serif" in src/Makefile and build it by yourself. If you are having trouble with building, I can build it for you, if you like.

i appreciate your help @zlate42. i have managed to build with sans font.
