### ISSUE TITLE
Does atomic mulitplication exist?

### ISSUE THREAD

**Issue by g-berthiaume** [beejjorgensen/bgc#134]
Question for the [atomic chapter](https://github.com/beejjorgensen/bgc/blob/8dfd0e7a0472d587dd3a7e26f2be14e9b2cd445c/src/bgc_part_3490_atomics.md?plain=1#L522):

In his 2017 cppcon talk, Fedor Pikus [mentionned](https://youtu.be/ZQFzMfHIxng?si=DZRbmhCh8jJqy5s2&t=727) that there was no atomic multiplier in C++ (`a *= b` won't compile). 
This seems to be in conflict with what is mentionned in the atomic chapter.

What do you think? Am I mistaken? Is there a difference between C and C++ ? 

Thanks for your work.

**Comment by beejjorgensen** [comment]
I could see why it wouldn't have it (since a 64-bit mult would have a 128-bit result), but the C spec doesn't seem to have a restriction against it.

In the section on compound assignment, it says:

> **For the other operators** _[including *=]_, **the left operand shall have atomic**, qualified, or unqualified arithmetic **type**, and (considering the type the left operand would have after lvalue conversion) each operand shall have arithmetic type consistent with those allowed by the corresponding binary operator.

So a difference between languages, perhaps...?

**Comment by g-berthiaume** [comment]
After testing, this seems to be the case !
https://godbolt.org/z/fsoMPWacG

Thanks for your answer.

**Comment by beejjorgensen** [comment]
Thanks for taking the time to test it out!
