### ISSUE TITLE
Incorrect note in `Single-Line Status Updates' section

### ISSUE THREAD

**Issue by macarc** [beejjorgensen/bgc#140]
Thank you for this guide!

In section `21.1.2.1`, the code description says:
> (Note this makes use of the non-standard POSIX function sleep() from <unistd.h>—if you’re not on a Unix-like, search for your platform and sleep for the equivalent.)

However, the code example uses `thrd_sleep()` from `<threads.h>`, not `sleep()` from `<unistd.h>`.

Section on website: https://beej.us/guide/bgc/html/split/characters-and-strings-ii.html#single-line-status-updates
Section in markdown: https://github.com/beejjorgensen/bgc/blob/main/src/bgc_part_1700_strings2.md#single-line-status-updates

**Comment by beejjorgensen** [comment]
Thanks! Fixed in the next rev.
