### ISSUE TITLE
18.1 Command Line Arguments -> include an explanation

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#15]
In the section you have the following program
```
int main(int argc, char **argv)
{
    int total = 0;

    for (int i = 0; i < argc; i++) {
        int value = atoi(argv[i]);  // Use strtol() for better error handling

        total += value;
    }

    printf("%d\n", total);
}
```

I would like to have one line of explanation around the tradeoff you went through when designing that program.
Something like.
- Instead of starting from index 1, I decided to start from index 0 for the program to be more concise. Starting form 1 would mean adding a line to explicitely the case of 0 arguments
- The other advantage of starting from 0 is that the atoi function will just convert the name of the program to 0.

Your reasoning might have been different. That decision to start from 0 is a little surprising (to me), adding a sentence to explain, would not hurt, I think.

**Comment by beejjorgensen** [comment]
It's actually just a bug, plain and simple. :) I meant to start at 1. Fixed!

Thanks!
