### ISSUE TITLE
19.2 Simple Macros: explaining a little further macro use

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#17]
You mention in the chapter that macro can be used to define constants.
What is the differences with just using a `cont float pi = 3.14`. Why would you choose one vs the other?
What are the tradeoff, advantages, disadvantages?
Maybe something around memory allocation? Or maybe it's just convention?

**Comment by beejjorgensen** [comment]
I had a couple paragraphs on this, but they read in the opposite sense as I intended. Modified to:

> Overall, this gives you a way to define constant values that are effectively global and can be used _any_ place. Even in those places where a `const` variable won't work, e.g. in `switch` `case`s and fixed array lengths.
>
>That said, the debate rages online whether a typed `const` variable is better than `#define` macro in the general case.
>
> It can also be used to replace or modify keywords, a concept completely foreign to `const`, though this practice should be used sparingly.

LMK if that still needs work.

**Comment by happysalada** [comment]
Thanks, Looks good to me
