### ISSUE TITLE
20.6.1 Non-Adjacent Bit-Fields: a little more explanation

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#19]
In the chapter you have
```
    struct foo {            // sizeof(struct foo) == 12 (for me)
        unsigned int a:1;
        unsigned int c:1;
        unsigned int b;
        unsigned int d;
    };
```
adding an explanation of why it is 12 would be great. It wasn't obvious to me at all.
- a and c get packed together into 4 bytes
- b is an unsigned int so 4 bytes
- same with d
- the total is 12 bytes

**Comment by happysalada** [comment]
also adding the explanation for the following example, would be great too
```
    struct foo {
        unsigned int a:1;
        unsigned int b:2;
        unsigned int :0;   // <--Zero-width unnamed bit-field
        unsigned int c:3;
        unsigned int d:4;
    };
```

- a and b get packed together into 4 bytes (both are unsigned int, and 3 bits fit into 36)
- c and d get packed together into 4 bytes (7 bits fit into 36)
- the resulting size is 8 bytes

**Comment by beejjorgensen** [comment]
Added more clarification there. Thanks!
