### ISSUE TITLE
27.9.3 I/O Functions: suggestion: add full function signature

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#21]
from this chapter on you give useful function descriptions.
It would be great to have the full function signature. I don't think it adds too much character and it helps the reader understand how the function works and to read code.

**Comment by beejjorgensen** [comment]
I don't want to put the signatures in those tables because it will make them overflow. But don't worry, I have a plan. :) I'm going to link those to the appropriate functions in the reference sections.

I just haven't written them all yet. :)
