### ISSUE TITLE
Why are VLAs banned from the linux kernel

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#28]
In the VLA chapter you mention that you will explain later why VLA are banned in the linux kernel.

Using goto and longjmp, you mention some caveats.

You also mention that longjmp is rarely used.
goto has been frowned upon a lot, so it wouldn't seem like the reason why VLA would be banned.
I'm not sure why, but would be interested to have a clear answer (even 1 or 2 lines somewhere).

**Comment by beejjorgensen** [comment]
"I'll talk about that later" is code for "I'll forget about this when it comes time to mention it later." ;)

Added some context to the next release. Cheers!

> VLAs have been banned from the Linux kernel due for a few reasons:
> 
> * Lots of places they were used should have just been fixed-size.
> * The code behind VLAs is slower (to a degree that most people wouldn't
>   notice, but makes a difference in an operating system).
> * VLAs are not supported to the same degree by all C compilers.
> * Stack size is limited, and VLAs go on the stack. If some code
>   accidentally (or maliciously) passes a large value into a kernel
>   function that allocates a VLA, _Bad Things_™ could happen.
> 
> Other folks online point out that there's no way to detect a VLA's
> failure to allocate, and programs that suffered such problems would
> likely just crash. While fixed-size arrays also have the same issue,
> it's far more likely that someone accidentally make a _VLA Of Unusual
> Size_ than somehow accidentally declare a fixed-size, say, 30 megabyte
> array.
