### ISSUE TITLE
37.1 The Bit-Sized Types: precisions on the fast type

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#30]
Would be great to have a couple of line detailing the fast in the fast type.
How fast is it? Any kind of qualifier would be good. Just to give you an idea of when you should be reaching for those

**Comment by beejjorgensen** [comment]
I wish I could even say. The spec is intentionally value on this issue other than to say it's the fastest available on that particular hardware. It doesn't say by how much.

But added some copy to that effect. Thanks for the suggestion!

> How much faster is `fast`? Definitely maybe some amount faster.
> Probably. The spec doesn't say how much faster, just that they'll be the
> fastest on this architecture. Most C compilers are pretty good, though,
> so you'll probably only see this used in places where the most possible
> speed needs to be guaranteed (rather than just hoping the compiler is
> producing pretty-dang-fast code, which it is).
