### ISSUE TITLE
39.4 Creating and Waiting for Threads: NOTE THIS

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#31]
in that chapter you have a // NOTE THIS
I think what you want to highlight is the pass by reference `&i` to show later the race condition.
On the line with the comment the expression is quite long. Therefore the `THIS` is not immediately obvious.
How about changing `// NOTE THIS` to `//NOTE THE &i`

**Comment by beejjorgensen** [comment]
Good call out. Thanks!
