### ISSUE TITLE
39.4 Creating and Waiting for Threads: why does run take a pointer to void

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#32]

**Comment by happysalada** [comment]
In the chapter, you've talked about `thrd_start_t` which is `a pointer to a function that takes an int* as an argument, and returns an int`
However you define run like this `int run(void *arg)` and then you explicitely cast the `*arg` to an `*int`.
Why not declare it as an `* int` in the first place. That's what the definition of `thrd_start_t` intends right?

**Comment by beejjorgensen** [comment]
Yup that's just wrong in the text. `thrd_start_t` is `int (*)(void*)`. Fixed.
