### ISSUE TITLE
39.4 free in the first code example

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#33]
I copied here your first code example with the race condition
```
#include <stdio.h>
#include <threads.h>

int run(void *arg)
{
    int i = *(int*)arg;

    free(arg);

    printf("THREAD %d: running!\n", i);

    return i;
}

#define THREAD_COUNT 5

int main(void)
{
    thrd_t t[THREAD_COUNT];

    int i;

    printf("Launching threads...\n");
    for (i = 0; i < THREAD_COUNT; i++)
        thrd_create(t + i, run, &i);   // <--- NOTE THIS

    printf("Doing other things while the thread runs...\n");
    printf("Waiting for thread to complete...\n");

    for (int i = 0; i < THREAD_COUNT; i++) {
        int res;
        thrd_join(t[i], &res);

        printf("Thread %d complete!\n", res);
    }

    printf("All threads complete!\n");
}
```

I think it would be good to add a comment next to the `free(arg)` inside the run function.
My initial thought was that this would free `i` and cause undefined behavior.
I'm still not sure why we need to `free(arg)` though. arg is just a pointer to `i` that we created. We never `malloc` for it. Would it not live on the stack?

**Comment by beejjorgensen** [comment]
Another error. I'm glad you're watching for them. :) Deleted the `free()` to fix. Thanks!
