### ISSUE TITLE
39 lock free algorithm and concurrency

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#37]
First of all, thanks for a great chapter on concurrency!

I'm wondering if you could consider talking about lock free algorithms for concurrency.
stuff like memory barriers, READ_ONCE, smp_store_release, smp_load_acquire, CAS and the like.
I know this stuff is not simple, just for you to consider. I would personally be super interested.

**Comment by beejjorgensen** [comment]
Thanks!

Yeah, a lot of that stuff is in the works when I get to writing the atomics chapter. But it'll be a little bit because I'm still learning it myself. :) Definitely complex, but I'm getting there and have a skeleton outline for how I'm going to approach it.

**Comment by happysalada** [comment]
Amazing, super looking forward to it!

Did you consider making a changelog?
Nothing too complex, but just something with chapters added.
If you combine that with releases, it's an efficient mechanism to tell your readers that something new is coming.
