### ISSUE TITLE
40: errno

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#39]
There is only a brief mention of errno in chapter 36 and one in chapter 40
Both of those mentions don't really explain what it is or how it is useful.
I would love to have an explanation somewhere.
(let me know if I've missed it)

**Comment by beejjorgensen** [comment]
I added an errno reference section, but I'm not sure that's quite enough. Leaving it open for now as a reminder. Cheers!

**Comment by happysalada** [comment]
Thanks, personally it looks good to me
