### ISSUE TITLE
Improvement: 3.2.1 The sizeof Operator -> Define %zu before using it

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#6]
Hey, 

   Amazing guide (I haven't read all of it yet), I love how it doesn't assume any prior knowledge and goes through everything.

   One tiny detail is that in part 3.2.1 The sizeof Operator, you use printf with %zu. How about giving a brief definition about it? You've defined %s %d and %f previously.

Thanks again for the great guide!

**Comment by beejjorgensen** [comment]
Added comment to next revision. Thanks so much!

**Comment by happysalada** [comment]
@beejjorgensen Thanks for taking care of this so quickly ❤️
