### ISSUE TITLE
4.2: (suggestion) Mention that implicit function declaration has been removed from the C spec

### ISSUE THREAD

**Issue by alexeikm** [beejjorgensen/bgc#69]
See [this PDF](http://www.open-std.org/jtc1/sc22/wg14/www/C99RationaleV5.10.pdf) (page 62), this might help programmers who are trying to refresh/improve their C knowledge through your book avoid such things. 

Implicit declaration is mentioned in section 17.1, and although you've recommended against using it, saying that it's non-standard is more explicit, and putting this in Chapter 4 makes more sense imho.

**Comment by beejjorgensen** [comment]
Good ideas. Cleaned it up a bit in both places.
