### ISSUE TITLE
6.6.1 Getting a Pointer to an Array -> typo: gives is

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#7]
In section 6.6.1 you have the following sentence

`But hold on a second–isn’t p an int*? And *p gives is 11, same as a[0]? Yessss.`
Maybe remove the `is` in `gives is`?
Or add a `What` as in `And what *p gives is 11, ...`?

**Comment by beejjorgensen** [comment]
"gives us 11" is what I was aiming for. Fixed in upcoming. Thanks!
