### ISSUE TITLE
9.6 Binary File I/O -> detail a bit sizeof bytes

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#8]
In 6.2 you say that getting the size of an array is impossible.

In 9.6 you use the following code
```
 unsigned char bytes[] = {5, 37, 0, 88, 255, 12};

    fp = fopen("output.bin", "wb");  // wb mode for "write binary"!

    // In the call to fwrite, the arguments are:
    //
    // * Pointer to data to write
    // * Size of each "piece" of data
    // * Count of each "piece" of data
    // * FILE*

    fwrite(bytes, sizeof(char), sizeof bytes, fp);
```

You give an explanation after, but just reading it, makes me think that the sizeof operator can give you the size of an array. To be clear, i would expect something to say why sizeof bytes returns 6.

This might be my own interpretation of things that is wrong. Feel free to close the issue if you think it's irrelevant.
Just thought you might want to know.

**Comment by beejjorgensen** [comment]
This sounds like something I should clarify a bit based on your feedback. It's definitely something that can bite people.

```
void foo(char c[128])
{
    char d[256];

    printf("%zu\n", sizeof c);  // probably 8, unexpectedly
    printf("%zu\n", sizeof d);  // 256, as expected
}
```

Sizeof gives the size of the object, to be sure, but when passing the array to a function, that information is lost (since you can't actually pass an array to a function--you can only pass a pointer to the first element).

I'll see what I can do to clarify. Cheers!

**Comment by happysalada** [comment]
My comment was maybe more related to the fact that
```
{
   unsigned char bytes[] = {5, 37};
   int nums[] = {1, 2};
   printf("%zu\n", sizeof bytes);  // 2*1 = 2
   printf("%zu\n", sizeof nums);  // 2*4 = 8
}
```
My understanding is that the sizeof operator for an array returns the sizeof one element multiplied by the number of elements. Since char are only 1 byte, this is why that example in the book works. If it was an array of ints, it wouldn't work the same right? 
I would say if that is the thing that i would have wanted to be clear.

**Comment by beejjorgensen** [comment]
I've added some to clarify... I'll drive it home a little more.
