### ISSUE TITLE
9.6.1 struct and Number Caveats -> duplicated sentence

### ISSUE THREAD

**Issue by happysalada** [beejjorgensen/bgc#9]
Not sure if it was on purpose, but the sentence
`And the same compiler on different architectures could do it differently` is duplicated.

**Comment by beejjorgensen** [comment]
It's actually subtly different. :)

And the same compiler on **different** architectures could do it differently.
And the same compiler on **the same** architectures could do it differently.

**Comment by happysalada** [comment]
My bad!
