### ISSUE TITLE
Missing "(" on sizeof operator

### ISSUE THREAD

**Issue by Antonio-Kim** [beejjorgensen/bgc#90]
On Page 17 of the book in pdf - section 3.2.7 The sizeof Opeartor - an example is given using sizeof operator:

```C
int a = 999;

printf("%zu\n", sizeof a); // Prints 4 on my system
printf("%zu\n", sizeof(2 + 7)); // Prints 4 on my system
printf("%zu\n", sizeof 3.14); // Prints 8 on my system
// If you need to print out negative size_t values, use %zd
```

the first line of sizeof operation requires "(" before a in order to work. Thus, the proper code should be:

```C
int a = 999;

printf("%zu\n", sizeof (a)); // Prints 4 on my system
printf("%zu\n", sizeof(2 + 7)); // Prints 4 on my system
printf("%zu\n", sizeof 3.14); // Prints 8 on my system
// If you need to print out negative size_t values, use %zd
```

Cheers,

**Comment by beejjorgensen** [comment]
This actually isn't the case. `sizeof` with an expression doesn't require the parens. `sizeof` with a type _does_, however.
